version: '3.8'

services:
  mysql:
    image: mysql:8
    container_name: mysql-server
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - ${BACKEND_NETWORK}

  site1:
    build:
      context: ./sites/site1
      dockerfile: ../../docker/php/Dockerfile
    container_name: site1
    environment:
      DB_HOST: mysql
      DB_DATABASE: site1_db
      DB_USERNAME: ${MYSQL_USER}
      DB_PASSWORD: ${MYSQL_PASSWORD}
    depends_on:
      - mysql
    networks:
      - ${BACKEND_NETWORK}
      - ${FRONTEND_NETWORK}

  nginx:
    image: nginx:latest
    container_name: nginx-proxy
    restart: always
    volumes:
      - ./docker/nginx/conf.d:/etc/nginx/conf.d
    ports:
      - "${NGINX_PORT}:80"
    depends_on:
      - site1
    networks:
      - ${FRONTEND_NETWORK}

volumes:
  mysql_data:

networks:
  backend:
  frontend:
